# CAN unit tests
#
# Type the following command to launch start the tests:
# $ sudo bash test/run_tests -t test/can.uts -F

% CAN unit tests

+ Configuration of scapy3

= Load CAN_addon
~ conf command
from scapy.layers.can import CAN, CANSocket, srcan

= Setup string for vcan
~ conf command
bashCommand = "/bin/bash -c 'sudo modprobe vcan; sudo ip link add name vcan0 type vcan; sudo ip link set dev vcan0 up'"

= Load os
~ conf command
import os
import threading
from time import sleep

= Setup vcan0
~ conf command
0 == os.system(bashCommand)

+ Basic Packet Tests()
= CAN Packet init

canframe = CAN(id=0x7ff,dlc=8,data=b'\x01\x02\x03\x04\x05\x06\x07\x08')
bytes(canframe) == b'\xff\x07\x00\x00\x08\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08'

= DLC greater than 8
canframe = CAN(id=0x7ff,dlc=9,data=b'\x01\x02\x03\x04\x05\x06\x07\x08')
print(len(canframe.data))
canframe.dlc = len(canframe.data)
bytes(canframe) == b'\xff\x07\x00\x00\x08\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08'

+ Basic Socket Tests()
= CAN Socket Init

sock1 = CANSocket(iface="vcan0")

= CAN Socket send recv

def sender():
    sleep(0.1)
    sock2 = CANSocket(iface="vcan0")
    sock2.send(CAN(id=0x7ff,dlc=8,data=b'\x01\x02\x03\x04\x05\x06\x07\x08'))

thread = threading.Thread(target=sender)
thread.start()

rx = sock1.recv()
rx == CAN(id=0x7ff,dlc=8,data=b'\x01\x02\x03\x04\x05\x06\x07\x08')

= CAN Socket sr1

tx = CAN(id=0x7ff,dlc=8,data=b'\x01\x02\x03\x04\x05\x06\x07\x08')
tx.sent_time == 0
thread = threading.Thread(target=sender)
thread.start()
rx = None
rx = sock1.sr1(tx)
tx == rx
tx.sent_time > rx.time
rx.time > 0

= srcan

tx = CAN(id=0x7ff,dlc=8,data=b'\x01\x02\x03\x04\x05\x06\x07\x08')
tx.sent_time == 0
thread = threading.Thread(target=sender)
thread.start()
rx = None
rx = srcan(tx, "vcan0", timeout=1)
rx = rx[0][0][1]
tx == rx
tx.sent_time > rx.time
rx.time > 0


+ PCAP CAN Tests()
= Write pcap file

rx = CAN(id=0x7ff,dlc=8,data=b'\x01\x02\x03\x04\x05\x06\x07\x08')
wrpcap('/tmp/scapyPcapTest.pcap', rx, append=False)
readPack = rdpcap('/tmp/scapyPcapTest.pcap', 1)
rx == readPack[0]

